In [2]:
import numpy as np
a = np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b= np.array([1.2, 3.2, 5.2])
a.dtype

dtype('int64')

In [9]:
c=np.array(1)
c

array(1)

In [10]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3, 2,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
import numpy as pi
pi.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])