In [2]:
import numpy as np #short array
a = np.array([2,8,5,8,3,4,1,0,9,6])
print(np.sort(a))
print(a.max())
print(a.min())
# print(a.sum())


[0 1 2 3 4 5 6 8 8 9]
9
0
46


In [21]:
array_a = np.array([1,2,3,4,])
array_b = np.array([5,6,6,7,])

print(np.concatenate((array_a, array_b))) #  #adding two array
print(array_a + array_b) #additions
# print(array_a - array_b) #substraction
print( array_a * array_b) #multification
print(array_b / array_a) #divition

[1 2 3 4 5 6 6 7]
[ 6  8  9 11]
[-4 -4 -3 -3]
[ 5 12 18 28]
[5.   3.   2.   1.75]


In [26]:
A = np.array([[2,3,5,6],[7,1,0,9]])
print(A.T)



[[2 7]
 [3 1]
 [5 0]
 [6 9]]
