In [1]:
# Scalar Matrix
import numpy as np
scalar_matrix = 5*np.eye(3)
print(scalar_matrix)

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [2]:
scalar_matrix = np.diag([3,3,3])
print(scalar_matrix)

[[3 0 0]
 [0 3 0]
 [0 0 3]]


In [4]:
lemda = 7
n=5
scalar_matrix= lemda*np.identity(n)
print(scalar_matrix)

[[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]
