In [1]:
# Trace of Matrix
import numpy as np
A = np.array([
    [1, 2, 5],
    [9, 8, 7],
    [6, 3, -4]
])

# method 01 

conj_A= np.trace(A)
print(conj_A)

#method 02
print(A.diagonal().sum())


5
5


In [8]:
# Transpose Conjugate  
# AH,A\*,AT
A_H = conj_A.T
print(A_H)

5


In [10]:
# Double Conjugate Transpose
A_H_H = A.conj().T.conj().T
print(A_H_H)

## (A)^HH = A

[[ 1  2  5]
 [ 9  8  7]
 [ 6  3 -4]]
