In [24]:
import numpy as np
A = np.array([
    [4, 2, 2],
    [2, 4, 2],
    [2, 2, 4]
])

A_Det = np.linalg.det(A)
print(round(A_Det))

32


In [25]:
inv = np.linalg.inv(A)
print(inv)

[[ 0.375 -0.125 -0.125]
 [-0.125  0.375 -0.125]
 [-0.125 -0.125  0.375]]


In [12]:
values, vectors = np.linalg.eig(A)
print(vectors)

[[-0.81649658  0.57735027 -0.32444284]
 [ 0.40824829  0.57735027 -0.48666426]
 [ 0.40824829  0.57735027  0.81110711]]


In [18]:
A = np.array([[2, 1],
              [1, 2]])

np.linalg.det(A)      # determinant
np.linalg.inv(A)      # inverse
np.linalg.eig(A)      # eigen


EigResult(eigenvalues=array([3., 1.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))